from pydantic import BaseModel, ConfigDict
from datetime import datetime
from typing import Optional, List

# --- BASE SCHEMAS ---
# These are used as the "Source of Truth" for data structure

class ClientLeadBase(BaseModel):
    name: str
    company: str
    status: Optional[str] = "Initial Call"
    value: float

class DocumentBase(BaseModel):
    filename: str
    client_name: str
    category: str

class TaskBase(BaseModel):
    client: str
    service: str
    assigned_to: str
    status: str
    last_action: Optional[str] = None

class TicketBase(BaseModel):
    subject: str
    client: str
    priority: str

# --- CREATE SCHEMAS ---
# These are used when receiving data from the React frontend (POST requests)

class ClientLeadCreate(ClientLeadBase):
    pass

class TaskCreate(TaskBase):
    pass

class TicketCreate(TicketBase):
    pass

# --- RESPONSE SCHEMAS ---
# These are used when sending data back to the frontend.
# They include the "id" and "timestamps" generated by Postgres.

class ClientLead(ClientLeadBase):
    id: int
    model_config = ConfigDict(from_attributes=True)

class Document(DocumentBase):
    id: int
    file_path: str
    upload_date: datetime
    model_config = ConfigDict(from_attributes=True)

class Task(TaskBase):
    id: int
    model_config = ConfigDict(from_attributes=True)

class Ticket(TicketBase):
    id: int
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)

class InvoiceBase(BaseModel):
    client: str
    amount: float
    status: Optional[str] = "Draft"

class InvoiceCreate(InvoiceBase):
    pass

class Invoice(InvoiceBase):
    id: int
    date: datetime
    model_config = ConfigDict(from_attributes=True)